name: llibrary
description: A Flutter project

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"


dependencies:
  flutter:
    sdk: flutter
  flutter_nfc_kit: ^3.3.1
  flutter_barcode_scanner: ^2.0.0
  http: ^0.13.3


# Other configurations, such as assets, fonts, etc., can be added here
flutter:
  uses-material-design: true
  assets:
    - assets/images/AASTlogo.png
    - assets/images/logo.png

  # Your Flutter specific configurations go here

